ALTER TABLE "PromoCode"
  ALTER COLUMN "creditUSD" SET DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "skillIds" JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS "grantLimitUSD" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "grantExpiresAt" TIMESTAMPTZ;

ALTER TABLE "PromoRedemption"
  ADD COLUMN IF NOT EXISTS "skillIds" JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS "creditLimitUSD" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "creditUsedUSD" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS "PromoRedemption_userId_expiresAt_idx"
  ON "PromoRedemption" ("userId", "expiresAt");

ALTER TABLE "SkillCall"
  ADD COLUMN IF NOT EXISTS "promoCoveredUSD" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "balanceChargedUSD" DOUBLE PRECISION;

ALTER TABLE "SkillRun"
  ADD COLUMN IF NOT EXISTS "promoRedemptionId" TEXT,
  ADD COLUMN IF NOT EXISTS "promoCoveredUSD" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "balanceChargedUSD" DOUBLE PRECISION;
