ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "pendingReferralProviderId" INTEGER;

CREATE TABLE IF NOT EXISTS "ProviderAttribution" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "newApiUserId" INTEGER NOT NULL,
    "skillId" INTEGER NOT NULL,
    "providerId" INTEGER NOT NULL,
    source TEXT NOT NULL DEFAULT 'referral',
    status TEXT NOT NULL DEFAULT 'active',
    "successThreshold" DOUBLE PRECISION NOT NULL DEFAULT 0.85,
    "minCalls" INTEGER NOT NULL DEFAULT 20,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "ProviderAttribution_newApiUserId_skillId_key"
ON "ProviderAttribution"("newApiUserId", "skillId");

CREATE INDEX IF NOT EXISTS "ProviderAttribution_newApiUserId_status_idx"
ON "ProviderAttribution"("newApiUserId", status);

CREATE INDEX IF NOT EXISTS "ProviderAttribution_providerId_status_idx"
ON "ProviderAttribution"("providerId", status);

ALTER TABLE "ProviderAttribution"
ADD CONSTRAINT "ProviderAttribution_providerId_fkey"
FOREIGN KEY ("providerId") REFERENCES "Provider"(id)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "ProviderAttribution"
ADD CONSTRAINT "ProviderAttribution_skillId_fkey"
FOREIGN KEY ("skillId") REFERENCES "Skill"(id)
ON DELETE RESTRICT ON UPDATE CASCADE;
