apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: grafana-postgresql-datasource
    access: proxy
    url: aws-1-eu-central-1.pooler.supabase.com:5432
    user: postgres.jtapfdkekjrqoqpuivuh
    database: postgres
    secureJsonData:
      password: dykzy5-xuvbob-tuvvoG
    jsonData:
      database: postgres
      sslmode: require
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    editable: true
